# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "183ba44346429003f4a8015caea9ebf7"
application_url = "https://simon-tracker-leon-dictionaries.trycloudflare.com"
embedded = true
name = "pratice-project"
handle = "pratice-project"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://simon-tracker-leon-dictionaries.trycloudflare.com/auth/callback",
  "https://simon-tracker-leon-dictionaries.trycloudflare.com/auth/shopify/callback",
  "https://simon-tracker-leon-dictionaries.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "pratice-project.myshopify.com"
automatically_update_urls_on_dev = true
